### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Dhairya296** [try2catch/SELF_LEARNING_JARVIS_AI#4]
Traceback (most recent call last):
  File "C:\Users\vilas\PycharmProjects\SELF_LEARNING_JARVIS_AI\main.py", line 57, in <module>
An HTTP error 400 occured: b'{\n  "error": {\n    "code": 400,\n    "message": "API key not valid. Please pass a valid API key.",\n    "errors": [\n      {\n        "message": "API key not valid. Please pass a valid API key.",\n        "domain": "global",\n        "reason": "badRequest"\n      }\n    ],\n    "status": "INVALID_ARGUMENT"\n  }\n}\n'
    YoutubeSearch(command, response).launch()
  File "C:\Users\vilas\PycharmProjects\SELF_LEARNING_JARVIS_AI\intents\youtube_search.py", line 45, in launch
    result = self.search()[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by Dhairya296** [comment]
Please Help

**Comment by try2catch** [comment]
Please check the search method. It's not returning anything.
